{"name": "test_assert_negative_case", "status": "failed", "statusDetails": {"message": "AssertionError: 2 + 2 != 5\nassert (2 + 2) == 5", "trace": "def test_assert_negative_case():\n>       assert (2 + 2) == 5, '2 + 2 != 5'\nE       AssertionError: 2 + 2 != 5\nE       assert (2 + 2) == 5\n\ntests\\pytest\\test_pytest.py:18: AssertionError"}, "start": 1758544959430, "stop": 1758544959430, "uuid": "acd26837-f27f-4bab-8b14-b95a5a9f2b95", "historyId": "031452ebcbddc980787dc8d54ce8e274", "testCaseId": "031452ebcbddc980787dc8d54ce8e274", "fullName": "tests.pytest.test_pytest#test_assert_negative_case", "labels": [{"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_pytest"}, {"name": "host", "value": "McSuit"}, {"name": "thread", "value": "28276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_pytest"}]}